### ISSUE TITLE
Failed to locate library: liblwjgl.dylib

### ISSUE THREAD

**Issue by p4paul** [aspose-3d/Aspose.3D-for-Java#9]
Hi, I was trying your example [RenderToBufferedImage](https://github.com/aspose-3d/Aspose.3D-for-Java/blob/master/src/java/examples/render/RenderToBufferedImage.java), but get the error:
```
Jun 06, 2022 1:32:53 PM org.junit.platform.launcher.core.EngineDiscoveryOrchestrator lambda$logTestDescriptorExclusionReasons$7
INFO: 0 containers and 1 tests were Method or class mismatch
[LWJGL] Failed to load a library. Possible solutions:
	a) Add the directory that contains the shared library to -Djava.library.path or -Dorg.lwjgl.librarypath.
	b) Add the JAR that contains the shared library to the classpath.
[LWJGL] Enable debug mode with -Dorg.lwjgl.util.Debug=true for better diagnostics.
[LWJGL] Enable the SharedLibraryLoader debug mode with -Dorg.lwjgl.util.DebugLoader=true for better diagnostics.

Failed to locate library: liblwjgl.dylib
java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl.dylib
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryUtil.<clinit>(MemoryUtil.java:97)
	at org.lwjgl.system.Pointer$Default.<clinit>(Pointer.java:61)
	at com.aspose.threed.mV.a(SourceFile:3140)
	at com.aspose.threed.mV.<init>(SourceFile:79)
	at com.aspose.threed.Renderer.a(SourceFile:681)
	at com.aspose.threed.Scene.render(SourceFile:795)
	at com.perforce.search.functional.Aspose3DTest.testCamera(Aspose3DTest.java:92)
	...snip...
```

I'm running on OS X (Intel) with Java 11.0.4 using Gradle:
```
repositories {
    mavenCentral()
    maven {
        url "https://repository.aspose.com/repo/"
    }
}
implementation 'com.aspose:aspose-3d:21.4'
```

Your other examples like LinearExtrusion seem ok?

**Comment by p4paul** [comment]
It seems to be a Mac OS X specific bug.  I ran the same example on Windows and it renders the objects to a PNG without error.

**Comment by p4paul** [comment]
Update:  I added Jars from https://www.lwjgl.org/customize and now get the error:
```
Renderer is not supported in this platform.
java.lang.UnsupportedOperationException: Renderer is not supported in this platform.
	at com.aspose.threed.nN.a(SourceFile:210)
	at com.aspose.threed.nN.<init>(SourceFile:79)
	at com.aspose.threed.Renderer.a(SourceFile:681)
	at com.aspose.threed.Scene.render(SourceFile:956)
```

Looking at the docs the Render seems to be supported on OS X with Java 11:
https://docs.aspose.com/3d/java/system-requirements/
(I have tried both Oracle and OpenJDK)

**Comment by asadalikhan90** [comment]
@p4paul 

We have noticed your similar inquiry in our forum. We will be responding to it shortly and you can please follow up on this issue there. (https://forum.aspose.com/t/missing-libraries-when-calling-render/247301/3)
